apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-cms
  labels:
    monokle.io/demo: vanilla-blue-cms
spec:
  replicas: 5
  selector:
    matchLabels:
      app: blue-cms
  template:
    metadata:
      labels:
        app: blue-cms
    spec:
      containers:
        - name: blue-cms
          image: blue-cms:latest
          ports:
            - name: http-web
              containerPort: 8080
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
      securityContext:
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: blue-cms
  labels:
    monokle.io/demo: vanilla-blue-cms
spec:
  selector:
    app: blue-cms
  ports:
    - name: http-web
      protocol: TCP
      port: 80
      targetPort: 8080
